"""Known-fact CNF templates vendored from SymPy.

Generated by ``tools/regen_known_facts.py`` from
``sympy.assumptions.ask_generated.get_all_known_number_facts()`` and
``get_all_known_matrix_facts()``; do not edit by hand.

Provenance: sympy/sympy at commit
ddbb536d7e803e4c38d5d5808ad1217368b12655, BSD-licensed; see
``reasoning/LICENSE.sympy``.  That commit is pinned as the ``sympy`` extra in
``pyproject.toml``.

Clause literals are 1-based predicate indices (negative means negated), and
both the literals inside a clause and the clause list itself are stored in
sorted order.  Predicate order is ``sorted(..., key=str)`` over the SymPy
predicates, exactly what the inline template compiler used before this table
was vendored, so predicate indices are stable.
"""

from __future__ import annotations

NUMBER_PREDICATES: tuple[str, ...] = (
    "algebraic",
    "antihermitian",
    "commutative",
    "complex",
    "composite",
    "even",
    "extended_negative",
    "extended_nonnegative",
    "extended_nonpositive",
    "extended_nonzero",
    "extended_positive",
    "extended_real",
    "finite",
    "hermitian",
    "imaginary",
    "infinite",
    "integer",
    "irrational",
    "negative",
    "negative_infinite",
    "nonnegative",
    "nonpositive",
    "nonzero",
    "odd",
    "positive",
    "positive_infinite",
    "prime",
    "rational",
    "real",
    "transcendental",
    "zero",
)

NUMBER_CLAUSES: tuple[tuple[int, ...], ...] = (
    (-31, -26),
    (-31, -25),
    (-31, -20),
    (-31, -19),
    (-31, 2, 14),
    (-31, 6),
    (-31, 8),
    (-31, 9),
    (-31, 12),
    (-31, 21),
    (-31, 22),
    (-31, 29),
    (-30, -1),
    (-30, 4),
    (-29, -15),
    (-29, 4),
    (-29, 14),
    (-29, 18, 28),
    (-29, 19, 25, 31),
    (-28, -18),
    (-28, 1),
    (-28, 29),
    (-27, -5),
    (-27, 17),
    (-27, 25),
    (-26, -25),
    (-26, -20),
    (-26, -19),
    (-26, 8),
    (-26, 10),
    (-26, 11),
    (-26, 12),
    (-26, 16),
    (-25, -20),
    (-25, -19),
    (-25, -6, 5, 27),
    (-25, 8),
    (-25, 10),
    (-25, 11),
    (-25, 12),
    (-25, 21),
    (-25, 23),
    (-25, 29),
    (-24, -6),
    (-24, 17),
    (-23, 19, 25),
    (-22, 19, 31),
    (-21, 25, 31),
    (-20, -19),
    (-20, 7),
    (-20, 9),
    (-20, 10),
    (-20, 12),
    (-20, 16),
    (-19, 7),
    (-19, 9),
    (-19, 10),
    (-19, 12),
    (-19, 22),
    (-19, 23),
    (-19, 29),
    (-18, 29),
    (-17, 6, 24),
    (-17, 28),
    (-16, -13),
    (-16, 3),
    (-15, 2),
    (-15, 4),
    (-13, 3),
    (-12, 19, 20, 25, 26, 31),
    (-11, 25, 26),
    (-10, 19, 20, 25, 26),
    (-9, 19, 20, 31),
    (-8, 25, 26, 31),
    (-7, 19, 20),
    (-6, 17),
    (-5, 17),
    (-5, 25),
    (-4, 1, 30),
    (-4, 13),
    (-1, 4),
)

MATRIX_PREDICATES: tuple[str, ...] = (
    "complex_elements",
    "diagonal",
    "fullrank",
    "integer_elements",
    "invertible",
    "lower_triangular",
    "normal",
    "orthogonal",
    "positive_definite",
    "real_elements",
    "singular",
    "square",
    "symmetric",
    "triangular",
    "unit_triangular",
    "unitary",
    "upper_triangular",
)

MATRIX_CLAUSES: tuple[tuple[int, ...], ...] = (
    (-17, -6, 2),
    (-17, 14),
    (-16, -10, 8),
    (-16, 5),
    (-16, 7),
    (-15, 14),
    (-14, 6, 17),
    (-13, 12),
    (-12, -3, 5),
    (-11, -5),
    (-10, 1),
    (-9, 5),
    (-8, 9),
    (-8, 16),
    (-7, 12),
    (-6, 14),
    (-5, 3),
    (-5, 12),
    (-4, 10),
    (-2, 6),
    (-2, 7),
    (-2, 13),
    (-2, 17),
    (5, 11),
)


def template(numbers: bool, matrices: bool) -> tuple[
        tuple[str, ...], tuple[tuple[int, ...], ...]]:
    """Return the merged template for the requested fact families.

    The predicate order is the sorted union of the requested families, so
    indices do not depend on which families are selected.  Merged clauses are
    re-encoded to the union indices and returned sorted.
    """
    if not numbers and not matrices:
        return (), ()
    if numbers and not matrices:
        return NUMBER_PREDICATES, NUMBER_CLAUSES
    if matrices and not numbers:
        return MATRIX_PREDICATES, MATRIX_CLAUSES
    names = tuple(sorted(set(NUMBER_PREDICATES) | set(MATRIX_PREDICATES)))
    index = {name: position + 1 for position, name in enumerate(names)}
    clauses: list[tuple[int, ...]] = []
    for predicates, table in (
            (NUMBER_PREDICATES, NUMBER_CLAUSES),
            (MATRIX_PREDICATES, MATRIX_CLAUSES)):
        local = {
            position + 1: index[name]
            for position, name in enumerate(predicates)
        }
        clauses.extend(
            tuple(local[literal] if literal > 0 else -local[-literal]
                  for literal in clause)
            for clause in table
        )
    return names, tuple(sorted(set(clauses)))
