"""Regenerate ``reasoning/knownfacts.py`` from the installed SymPy.

SymPy's ``ask_generated`` module defines the known-fact CNF templates as
``set`` objects of literal types, and the core must not import SymPy.  This
script vendors those templates once, in a canonical and diffable form, so the
SymPy adapter can build ``_known_template`` from checked-in data.

Run it after bumping the pinned SymPy commit::

    python tools/regen_known_facts.py

``--check`` renders the file in memory and exits non-zero when the checked-in
table differs, which is useful in review.

The emitted predicate order is ``sorted(..., key=str)`` over the SymPy
predicates, exactly like the old inline ``_known_template``.  All predicates
are ``Q.<name>``, so that order equals sorting the plain names.  Clause
literals are 1-based predicate indices (negative for negated literals);
literals inside a clause and the clause list itself are sorted, because the
SymPy fact sets are unordered.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable

from sympy.assumptions.ask_generated import (
    get_all_known_matrix_facts, get_all_known_number_facts,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "reasoning" / "knownfacts.py"
SYMPY_COMMIT = "ddbb536d7e803e4c38d5d5808ad1217368b12655"

_DOCSTRING = '''"""Known-fact CNF templates vendored from SymPy.

Generated by ``tools/regen_known_facts.py`` from
``sympy.assumptions.ask_generated.get_all_known_number_facts()`` and
``get_all_known_matrix_facts()``; do not edit by hand.

Provenance: sympy/sympy at commit
{commit}, BSD-licensed; see
``reasoning/LICENSE.sympy``.  That commit is pinned as the ``sympy`` extra in
``pyproject.toml``.

Clause literals are 1-based predicate indices (negative means negated), and
both the literals inside a clause and the clause list itself are stored in
sorted order.  Predicate order is ``sorted(..., key=str)`` over the SymPy
predicates, exactly what the inline template compiler used before this table
was vendored, so predicate indices are stable.
"""'''.format(commit=SYMPY_COMMIT)

_MERGE = '''

def template(numbers: bool, matrices: bool) -> tuple[
        tuple[str, ...], tuple[tuple[int, ...], ...]]:
    """Return the merged template for the requested fact families.

    The predicate order is the sorted union of the requested families, so
    indices do not depend on which families are selected.  Merged clauses are
    re-encoded to the union indices and returned sorted.
    """
    if not numbers and not matrices:
        return (), ()
    if numbers and not matrices:
        return NUMBER_PREDICATES, NUMBER_CLAUSES
    if matrices and not numbers:
        return MATRIX_PREDICATES, MATRIX_CLAUSES
    names = tuple(sorted(set(NUMBER_PREDICATES) | set(MATRIX_PREDICATES)))
    index = {name: position + 1 for position, name in enumerate(names)}
    clauses: list[tuple[int, ...]] = []
    for predicates, table in (
            (NUMBER_PREDICATES, NUMBER_CLAUSES),
            (MATRIX_PREDICATES, MATRIX_CLAUSES)):
        local = {
            position + 1: index[name]
            for position, name in enumerate(predicates)
        }
        clauses.extend(
            tuple(local[literal] if literal > 0 else -local[-literal]
                  for literal in clause)
            for clause in table
        )
    return names, tuple(sorted(set(clauses)))
'''


def _predicate_names(facts: Iterable[Any]) -> tuple[str, ...]:
    names = {literal.lit.name for clause in facts for literal in clause}
    return tuple(sorted(names))


def _canonical_clauses(facts: Iterable[Any],
                       names: tuple[str, ...]) -> tuple[tuple[int, ...], ...]:
    encoding = {name: index + 1 for index, name in enumerate(names)}
    clauses = set()
    for clause in facts:
        literals = sorted(
            -encoding[literal.lit.name] if literal.is_Not
            else encoding[literal.lit.name]
            for literal in clause)
        clauses.add(tuple(literals))
    return tuple(sorted(clauses))


def _render_names(names: tuple[str, ...]) -> str:
    return "\n".join(f'    "{name}",' for name in names)


def _render_clauses(clauses: tuple[tuple[int, ...], ...]) -> str:
    lines = []
    for clause in clauses:
        inner = ", ".join(str(literal) for literal in clause)
        suffix = "," if len(clause) == 1 else ""
        lines.append(f"    ({inner}{suffix}),")
    return "\n".join(lines)


def _render_table(name: str, names: tuple[str, ...],
                  clauses: tuple[tuple[int, ...], ...]) -> str:
    return (
        f"{name}_PREDICATES: tuple[str, ...] = (\n"
        f"{_render_names(names)}\n"
        f")\n\n"
        f"{name}_CLAUSES: tuple[tuple[int, ...], ...] = (\n"
        f"{_render_clauses(clauses)}\n"
        f")\n"
    )


def render(number_facts: Iterable[Any], matrix_facts: Iterable[Any]) -> str:
    number_names = _predicate_names(number_facts)
    matrix_names = _predicate_names(matrix_facts)
    overlap = set(number_names) & set(matrix_names)
    if overlap:
        raise ValueError(f"predicate name overlap: {sorted(overlap)}")
    return (
        _DOCSTRING
        + "\n\nfrom __future__ import annotations\n\n"
        + _render_table("NUMBER", number_names,
                        _canonical_clauses(number_facts, number_names))
        + "\n"
        + _render_table("MATRIX", matrix_names,
                        _canonical_clauses(matrix_facts, matrix_names))
        + _MERGE
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="exit non-zero if the checked-in file differs")
    args = parser.parse_args(argv)

    rendered = render(get_all_known_number_facts(),
                      get_all_known_matrix_facts())
    if args.check:
        current = OUTPUT.read_text()
        if current != rendered:
            print(f"{OUTPUT} is out of date", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date")
        return 0
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
